-- ═══════════════════════════════════════════════════════════════════════
--  0134 — El catalogo del marketplace, con tildes y eñes
--
--  El texto visible de `regb.module_catalog` (nombre, descripcion, lema,
--  problema, que incluye, a quien le sirve, preguntas y los titulos de las
--  pantallas) se escribio sin tildes: "Nomina", "Conciliacion bancaria",
--  "Codigos de barra", "al ano". Es lo primero que lee un cliente que va a
--  pagar, y se lee descuidado. Lo que cambia es SOLO texto: ningun id,
--  categoria, precio ni dependencia.
--
--  ── Por que reglas y no el texto entero ──────────────────────────────
--
--  Otras migraciones corrigen fichas concretas (la 0116 la de impuestos,
--  la 0124 la de captura de facturas). Reescribir cada campo con su texto
--  final pisaria en silencio cualquier ficha que otra migracion cambie
--  antes que esta. Aqui se aplican reglas por palabra (`\m...\M`, limite de
--  palabra) sobre lo que haya, asi que una frase nueva sale corregida y
--  una ya corregida no se toca.
--
--  Tres grupos, en este orden:
--   1. Frases que deciden lo ambiguo: interrogativos ("sabe quien te debe"
--      -> "sabe quién te debe"), "está" frente a "esta version", "sí"
--      afirmativo, "tú" y "él" pronombres, y preteritos que tambien son
--      sustantivos ("quien lo cambio" -> "cambió", pero "tipo de cambio").
--   2. Palabras que siempre llevan tilde en este catalogo (módulo,
--      nómina, crédito, -ción...), en minuscula, Capitalizada y MAYUSCULA.
--   3. Reglas de contexto: "esta" -> "está" salvo delante de version/vez/
--      primera; "cuanto" -> "cuánto" salvo "en cuanto" (en cuanto pasa);
--      "Si," / "Si -" al responder -> "Sí".
--
--  Los esquemas de texto (`screens[].mockup`) NO se tocan: son dibujos de
--  pantalla en ASCII y su ancho cuenta.
-- ═══════════════════════════════════════════════════════════════════════

create temporary table tildes_0134 (
  orden int primary key,
  patron text not null,
  reemplazo text not null
) on commit drop;

insert into tildes_0134 (orden, patron, reemplazo) values
  (1, '\mSabe a quien le debes, cuanto y cuando toca pagar\M', 'Sabe a quién le debes, cuánto y cuándo toca pagar'),
  (2, '\mSabe quien te debe, cuanto y desde cuando\M', 'Sabe quién te debe, cuánto y desde cuándo'),
  (3, '\mno hay a quien facturarle\M', 'no hay a quién facturarle'),
  (4, '\mno sabes a quien llamar\M', 'no sabes a quién llamar'),
  (5, '\mte dice a quien llamar\M', 'te dice a quién llamar'),
  (6, '\mSabe quien marco, a que hora y desde donde\M', 'Sabe quién marcó, a qué hora y desde dónde'),
  (7, '\mQuien hizo que, cuando y desde donde\M', 'Quién hizo qué, cuándo y desde dónde'),
  (8, '\mRegistra quien esta inscrito en que plan y cuanto aporta\M', 'Registra quién está inscrito en qué plan y cuánto aporta'),
  (9, '\mni quien lo cambio\M', 'ni quién lo cambió'),
  (10, '\msu historial y a quien le reporta\M', 'su historial y a quién le reporta'),
  (11, '\mdesde cuando trabaja, quien es su jefe\M', 'desde cuándo trabaja, quién es su jefe'),
  (12, '"cuanto anos tiene aqui"', '"cuántos años tiene aquí"'),
  (13, '"quien le reporta a quien"', '"quién le reporta a quién"'),
  (14, '\mA partir de quien le reporta a quien\M', 'A partir de quién le reporta a quién'),
  (15, '\mde quien firmo, cuando y sobre que version\M', 'de quién firmó, cuándo y sobre qué versión'),
  (16, '\(quien, cuando, desde que IP, sobre que version\)', '(quién, cuándo, desde qué IP, sobre qué versión)'),
  (17, '\mquien, cuando, por que y cuanto\M', 'quién, cuándo, por qué y cuánto'),
  (18, '-quien recibio, cuando, en que estado quedo la parada\M', '-quién recibió, cuándo, en qué estado quedó la parada'),
  (19, '\mo quien recibio cada entrega\M', 'o quién recibió cada entrega'),
  (20, '\mno tiene como saber que salio de la puerta y a quien\M', 'no tiene cómo saber qué salió de la puerta y a quién'),
  (21, '\mde a quien se le envio\M', 'de a quién se le envió'),
  (22, '\mregistra a quien se le envio y cuando\M', 'registra a quién se le envió y cuándo'),
  (23, '\mel rastro de quien ya pago\M', 'el rastro de quién ya pagó'),
  (24, '\mde a quien se le pidio, cuanto, y si ya pago\M', 'de a quién se le pidió, cuánto, y si ya pagó'),
  (25, '\mlo ve quien tu digas\M', 'lo ve quien tú digas'),
  (26, '\mQuien entrevisto, cuando y con que resultado\M', 'Quién entrevistó, cuándo y con qué resultado'),
  (27, '\mnadie sabe quien lo aprobo ni por que monto\M', 'nadie sabe quién lo aprobó ni por qué monto'),
  (28, '\mcuanto le queda a quien\M', 'cuánto le queda a quién'),
  (29, '\mQuien esta fuera y cuando\M', 'Quién está fuera y cuándo'),
  (30, '\mnadie sabe quien esta certificado en que,', 'nadie sabe quién está certificado en qué,'),
  (31, '\mSe registra el curso, quien se inscribio\M', 'Se registra el curso, quién se inscribió'),
  (32, '\mnadie tiene claro cuando toca renovar\M', 'nadie tiene claro cuándo toca renovar'),
  (33, '\mnadie puede probar cuando, desde donde, ni sobre cual version\M', 'nadie puede probar cuándo, desde dónde, ni sobre cuál versión'),
  (34, '\mni cuando terminan de depreciarse\M', 'ni cuándo terminan de depreciarse'),
  (35, '\mdecide cuando un equipo necesita\M', 'decide cuándo un equipo necesita'),
  (36, '-que se calculo, cuando-', '-qué se calculó, cuándo-'),
  (37, '\mni desde cuando, y el dia\M', 'ni desde cuándo, y el día'),
  (38, '\mde donde salio cada numero\M', 'de dónde salió cada número'),
  (39, '\mrecordando donde se quedo\M', 'recordando dónde se quedó'),
  (40, '\mSaber que hay, donde esta y cuanto vale\M', 'Saber qué hay, dónde está y cuánto vale'),
  (41, '\mnadie sabe donde se fue\M', 'nadie sabe dónde se fue'),
  (42, '\macordarse cual vence\M', 'acordarse cuál vence'),
  (43, '\mavisa en cual semana\M', 'avisa en cuál semana'),
  (44, '\mni cuales llevan\M', 'ni cuáles llevan'),
  (45, '\mnadie tiene con que probar\M', 'nadie tiene con qué probar'),
  (46, '\mlinea que trae y que no\M', 'línea qué trae y qué no'),
  (47, '\mno tiene con que hacer match\M', 'no tiene con qué hacer match'),
  (48, '\mtenga con que hacer match\M', 'tenga con qué hacer match'),
  (49, '\mde que parte del negocio\M', 'de qué parte del negocio'),
  (50, '\msaben a que empresa pertenecen\M', 'saben a qué empresa pertenecen'),
  (51, '\mmanual o de que asiento salio\M', 'manual o de qué asiento salió'),
  (52, '\mun lead saco 70\M', 'un lead sacó 70'),
  (53, '\my en que periodo\M', 'y en qué periodo'),
  (54, '\mno hay con que responderle\M', 'no hay con qué responderle'),
  (55, '\melige solo de que lote sacar\M', 'elige solo de qué lote sacar'),
  (56, '\mnadie recuerda que tasa se uso ese dia\M', 'nadie recuerda qué tasa se usó ese día'),
  (57, '\mguarda que tasas uso cada periodo\M', 'guarda qué tasas usó cada periodo'),
  (58, '\mcontra que comparar\M', 'contra qué comparar'),
  (59, '\mni a que precio quedo\M', 'ni a qué precio quedó'),
  (60, '\mni de que se le devolvio\M', 'ni de qué se le devolvió'),
  (61, '\mnadie sabe en que etapa esta cada candidato\M', 'nadie sabe en qué etapa está cada candidato'),
  (62, '\msaber que tan bien\M', 'saber qué tan bien'),
  (63, '\mnadie sabe que tasas de ITBIS\M', 'nadie sabe qué tasas de ITBIS'),
  (64, '\mcon que codigo de la DGII\M', 'con qué código de la DGII'),
  (65, '\mno tenga como probarlo\M', 'no tenga cómo probarlo'),
  (66, '\mCuando este listo\M', 'Cuando esté listo'),
  (67, '\mno este activa\M', 'no esté activa'),
  (68, '\maqui SI se hace\M', 'aquí SÍ se hace'),
  (69, '\mresuelto si se puede\M', 'resuelto sí se puede'),
  (70, '\mrechazado si se puede\M', 'rechazado sí se puede'),
  (71, '\mcerrado si es terminal\M', 'cerrado sí es terminal'),
  (72, '\mactivo si reserva\M', 'activo sí reserva'),
  (73, '\meso si sale\M', 'eso sí sale'),
  (74, '\mque TU configuraste\M', 'que TÚ configuraste'),
  (75, '\mlo que anotaste tu casi\M', 'lo que anotaste tú casi'),
  (76, '\mel banco registro y tu no\M', 'el banco registró y tú no'),
  (77, '\mhasta lo que tu decidas\M', 'hasta lo que tú decidas'),
  (78, '\mMAS lo que tu le retuviste\M', 'MÁS lo que tú le retuviste'),
  (79, '\mverlo el mismo\M', 'verlo él mismo'),
  (80, '\mordenes sin el,', 'órdenes sin él,'),
  (81, '\mcon el si fabricas\M', 'con él si fabricas'),
  (82, '\mque ya lo registro\M', 'que ya lo registró'),
  (83, '\mse pago -', 'se pagó -'),
  (84, '\mya pago\M', 'ya pagó'),
  (85, '\mse uso ese\M', 'se usó ese'),
  (86, '\mtasas que uso\M', 'tasas que usó'),
  (87, '\mse gasto de verdad\M', 'se gastó de verdad'),
  (88, '\mde verdad paso\M', 'de verdad pasó'),
  (89, '\mya paso\M', 'ya pasó'),
  (90, '\mque no paso por\M', 'que no pasó por'),
  (91, '\mse le envio\M', 'se le envió'),
  (92, '\mse rechazo\M', 'se rechazó'),
  (93, '\mse reembolso\M', 'se reembolsó'),
  (94, '\mquien compro\M', 'quien compró'),
  (95, '\mlo calculo el canal\M', 'lo calculó el canal'),
  (96, '\mme costo\M', 'me costó'),
  (97, '\mse completo\M', 'se completó'),
  (98, '\mnadie presupuesto\M', 'nadie presupuestó'),
  (99, '\mganancia o perdida\M', 'ganancia o pérdida'),
  (100, '\mmotivos de perdida\M', 'motivos de pérdida'),
  (101, '\mMotivo de perdida\M', 'Motivo de pérdida'),
  (102, '\mmotivo de perdida\M', 'motivo de pérdida'),
  (103, '-perdida en el camino\M', '-pérdida en el camino'),
  (104, '\mpagina publica\M', 'página pública'),
  (105, '\mde fabrica\M', 'de fábrica'),
  (106, '\mmas especifica\M', 'más específica'),
  (107, '\mFK autentica\M', 'FK auténtica'),
  (108, '\mfiscal valido\M', 'fiscal válido'),
  (109, '\mya termino\M', 'ya terminó'),
  (110, '\mque la genero\M', 'que la generó'),
  (111, '\mhoras reales tomo\M', 'horas reales tomó'),
  (112, '\mse gano\M', 'se ganó'),
  (113, '\mse planeo\M', 'se planeó'),
  (114, '\mlo reviso\M', 'lo revisó'),
  (115, '\mse aplico\M', 'se aplicó'),
  (116, '\maporto cada empresa\M', 'aportó cada empresa'),
  (117, '\mo cotizo\M', 'o cotizó'),
  (118, '\mnunca entro\M', 'nunca entró'),
  (119, '\mque ainda no existe\M', 'que todavía no existe'),
  (120, '\mlo entrego\M', 'lo entregó'),
  (121, '\mse calculo\M', 'se calculó'),
  (122, '\mlo calculo\M', 'lo calculó'),
  (123, '\mse envio\M', 'se envió'),
  (124, '\mcoincidente seria\M', 'coincidente sería'),
  (125, '\motra vez seria\M', 'otra vez sería'),
  (126, '¿Que\M', '¿Qué'),
  (127, '\mpor que\M', 'por qué'),
  (128, '\mPor que\M', 'Por qué'),
  (129, '\mprevisualizacion\M', 'previsualización'),
  (130, '\mPREVISUALIZACION\M', 'PREVISUALIZACIÓN'),
  (131, '\mPrevisualizacion\M', 'Previsualización'),
  (132, '\mautomaticamente\M', 'automáticamente'),
  (133, '\mAUTOMATICAMENTE\M', 'AUTOMÁTICAMENTE'),
  (134, '\mAutomaticamente\M', 'Automáticamente'),
  (135, '\mGeocodificacion\M', 'Geocodificación'),
  (136, '\mgeocodificacion\M', 'geocodificación'),
  (137, '\mGEOCODIFICACION\M', 'GEOCODIFICACIÓN'),
  (138, '\mExplicitamente\M', 'Explícitamente'),
  (139, '\mexplicitamente\M', 'explícitamente'),
  (140, '\mEXPLICITAMENTE\M', 'EXPLÍCITAMENTE'),
  (141, '\mAutenticacion\M', 'Autenticación'),
  (142, '\mautenticacion\M', 'autenticación'),
  (143, '\mAUTENTICACION\M', 'AUTENTICACIÓN'),
  (144, '\mCertificacion\M', 'Certificación'),
  (145, '\mCERTIFICACION\M', 'CERTIFICACIÓN'),
  (146, '\mcertificacion\M', 'certificación'),
  (147, '\mClasificacion\M', 'Clasificación'),
  (148, '\mclasificacion\M', 'clasificación'),
  (149, '\mCLASIFICACION\M', 'CLASIFICACIÓN'),
  (150, '\mconfiguracion\M', 'configuración'),
  (151, '\mConfiguracion\M', 'Configuración'),
  (152, '\mCONFIGURACION\M', 'CONFIGURACIÓN'),
  (153, '\mconsolidacion\M', 'consolidación'),
  (154, '\mConsolidacion\M', 'Consolidación'),
  (155, '\mCONSOLIDACION\M', 'CONSOLIDACIÓN'),
  (156, '\mCriptografica\M', 'Criptográfica'),
  (157, '\mCRIPTOGRAFICA\M', 'CRIPTOGRÁFICA'),
  (158, '\mcriptografica\M', 'criptográfica'),
  (159, '\mPLANIFICACION\M', 'PLANIFICACIÓN'),
  (160, '\mplanificacion\M', 'planificación'),
  (161, '\mPlanificacion\M', 'Planificación'),
  (162, '\mREFRIGERACION\M', 'REFRIGERACIÓN'),
  (163, '\mRefrigeracion\M', 'Refrigeración'),
  (164, '\mrefrigeracion\M', 'refrigeración'),
  (165, '\mAdjudicacion\M', 'Adjudicación'),
  (166, '\mADJUDICACION\M', 'ADJUDICACIÓN'),
  (167, '\madjudicacion\M', 'adjudicación'),
  (168, '\mamortizacion\M', 'amortización'),
  (169, '\mAMORTIZACION\M', 'AMORTIZACIÓN'),
  (170, '\mAmortizacion\M', 'Amortización'),
  (171, '\mcalificacion\M', 'calificación'),
  (172, '\mCalificacion\M', 'Calificación'),
  (173, '\mCALIFICACION\M', 'CALIFICACIÓN'),
  (174, '\mcapacitacion\M', 'capacitación'),
  (175, '\mCAPACITACION\M', 'CAPACITACIÓN'),
  (176, '\mCapacitacion\M', 'Capacitación'),
  (177, '\mComprobacion\M', 'Comprobación'),
  (178, '\mcomprobacion\M', 'comprobación'),
  (179, '\mCOMPROBACION\M', 'COMPROBACIÓN'),
  (180, '\mCONCILIACION\M', 'CONCILIACIÓN'),
  (181, '\mconciliacion\M', 'conciliación'),
  (182, '\mConciliacion\M', 'Conciliación'),
  (183, '\mCONFIRMACION\M', 'CONFIRMACIÓN'),
  (184, '\mConfirmacion\M', 'Confirmación'),
  (185, '\mconfirmacion\M', 'confirmación'),
  (186, '\mConstruccion\M', 'Construcción'),
  (187, '\mCONSTRUCCION\M', 'CONSTRUCCIÓN'),
  (188, '\mconstruccion\M', 'construcción'),
  (189, '\mConsultorias\M', 'Consultorías'),
  (190, '\mconsultorias\M', 'consultorías'),
  (191, '\mCONSULTORIAS\M', 'CONSULTORÍAS'),
  (192, '\mContratacion\M', 'Contratación'),
  (193, '\mcontratacion\M', 'contratación'),
  (194, '\mCONTRATACION\M', 'CONTRATACIÓN'),
  (195, '\mCONVERSACION\M', 'CONVERSACIÓN'),
  (196, '\mconversacion\M', 'conversación'),
  (197, '\mConversacion\M', 'Conversación'),
  (198, '\mDEPRECIACION\M', 'DEPRECIACIÓN'),
  (199, '\mDepreciacion\M', 'Depreciación'),
  (200, '\mdepreciacion\M', 'depreciación'),
  (201, '\mDISTRIBUCION\M', 'DISTRIBUCIÓN'),
  (202, '\mdistribucion\M', 'distribución'),
  (203, '\mDistribucion\M', 'Distribución'),
  (204, '\mfidelizacion\M', 'fidelización'),
  (205, '\mFIDELIZACION\M', 'FIDELIZACIÓN'),
  (206, '\mFidelizacion\M', 'Fidelización'),
  (207, '\mhomologacion\M', 'homologación'),
  (208, '\mHomologacion\M', 'Homologación'),
  (209, '\mHOMOLOGACION\M', 'HOMOLOGACIÓN'),
  (210, '\mnotificacion\M', 'notificación'),
  (211, '\mNOTIFICACION\M', 'NOTIFICACIÓN'),
  (212, '\mNotificacion\M', 'Notificación'),
  (213, '\mOPTIMIZACION\M', 'OPTIMIZACIÓN'),
  (214, '\moptimizacion\M', 'optimización'),
  (215, '\mOptimizacion\M', 'Optimización'),
  (216, '\mPresentacion\M', 'Presentación'),
  (217, '\mPRESENTACION\M', 'PRESENTACIÓN'),
  (218, '\mpresentacion\M', 'presentación'),
  (219, '\mPROGRAMACION\M', 'PROGRAMACIÓN'),
  (220, '\mProgramacion\M', 'Programación'),
  (221, '\mprogramacion\M', 'programación'),
  (222, '\msatisfaccion\M', 'satisfacción'),
  (223, '\mSatisfaccion\M', 'Satisfacción'),
  (224, '\mSATISFACCION\M', 'SATISFACCIÓN'),
  (225, '\mValorizacion\M', 'Valorización'),
  (226, '\mvalorizacion\M', 'valorización'),
  (227, '\mVALORIZACION\M', 'VALORIZACIÓN'),
  (228, '\mVERIFICACION\M', 'VERIFICACIÓN'),
  (229, '\mverificacion\M', 'verificación'),
  (230, '\mVerificacion\M', 'Verificación'),
  (231, '\mautomaticas\M', 'automáticas'),
  (232, '\mAutomaticas\M', 'Automáticas'),
  (233, '\mAUTOMATICAS\M', 'AUTOMÁTICAS'),
  (234, '\mAUTOMATICOS\M', 'AUTOMÁTICOS'),
  (235, '\mAutomaticos\M', 'Automáticos'),
  (236, '\mautomaticos\M', 'automáticos'),
  (237, '\mDeclaracion\M', 'Declaración'),
  (238, '\mDECLARACION\M', 'DECLARACIÓN'),
  (239, '\mdeclaracion\M', 'declaración'),
  (240, '\mDescripcion\M', 'Descripción'),
  (241, '\mDESCRIPCION\M', 'DESCRIPCIÓN'),
  (242, '\mdescripcion\M', 'descripción'),
  (243, '\mDiagnostico\M', 'Diagnóstico'),
  (244, '\mDIAGNOSTICO\M', 'DIAGNÓSTICO'),
  (245, '\mdiagnostico\M', 'diagnóstico'),
  (246, '\mELECTRONICA\M', 'ELECTRÓNICA'),
  (247, '\mElectronica\M', 'Electrónica'),
  (248, '\melectronica\M', 'electrónica'),
  (249, '\mEliminacion\M', 'Eliminación'),
  (250, '\mELIMINACION\M', 'ELIMINACIÓN'),
  (251, '\meliminacion\M', 'eliminación'),
  (252, '\mFacturacion\M', 'Facturación'),
  (253, '\mFACTURACION\M', 'FACTURACIÓN'),
  (254, '\mfacturacion\M', 'facturación'),
  (255, '\mFERRETERIAS\M', 'FERRETERÍAS'),
  (256, '\mferreterias\M', 'ferreterías'),
  (257, '\mFerreterias\M', 'Ferreterías'),
  (258, '\mFisicamente\M', 'Físicamente'),
  (259, '\mfisicamente\M', 'físicamente'),
  (260, '\mFISICAMENTE\M', 'FÍSICAMENTE'),
  (261, '\mFotografias\M', 'Fotografías'),
  (262, '\mFOTOGRAFIAS\M', 'FOTOGRAFÍAS'),
  (263, '\mfotografias\M', 'fotografías'),
  (264, '\mimportacion\M', 'importación'),
  (265, '\mIMPORTACION\M', 'IMPORTACIÓN'),
  (266, '\mImportacion\M', 'Importación'),
  (267, '\mINFORMACION\M', 'INFORMACIÓN'),
  (268, '\minformacion\M', 'información'),
  (269, '\mInformacion\M', 'Información'),
  (270, '\mInscripcion\M', 'Inscripción'),
  (271, '\mINSCRIPCION\M', 'INSCRIPCIÓN'),
  (272, '\minscripcion\M', 'inscripción'),
  (273, '\mIntegracion\M', 'Integración'),
  (274, '\mintegracion\M', 'integración'),
  (275, '\mINTEGRACION\M', 'INTEGRACIÓN'),
  (276, '\mLiquidacion\M', 'Liquidación'),
  (277, '\mLIQUIDACION\M', 'LIQUIDACIÓN'),
  (278, '\mliquidacion\M', 'liquidación'),
  (279, '\mNEGOCIACION\M', 'NEGOCIACIÓN'),
  (280, '\mnegociacion\M', 'negociación'),
  (281, '\mNegociacion\M', 'Negociación'),
  (282, '\mprospeccion\M', 'prospección'),
  (283, '\mPROSPECCION\M', 'PROSPECCIÓN'),
  (284, '\mProspeccion\M', 'Prospección'),
  (285, '\mREEXPRESION\M', 'REEXPRESIÓN'),
  (286, '\mReexpresion\M', 'Reexpresión'),
  (287, '\mreexpresion\M', 'reexpresión'),
  (288, '\mREQUISICION\M', 'REQUISICIÓN'),
  (289, '\mrequisicion\M', 'requisición'),
  (290, '\mRequisicion\M', 'Requisición'),
  (291, '\msuscripcion\M', 'suscripción'),
  (292, '\mSUSCRIPCION\M', 'SUSCRIPCIÓN'),
  (293, '\mSuscripcion\M', 'Suscripción'),
  (294, '\maceptacion\M', 'aceptación'),
  (295, '\mACEPTACION\M', 'ACEPTACIÓN'),
  (296, '\mAceptacion\M', 'Aceptación'),
  (297, '\mANTIGUEDAD\M', 'ANTIGÜEDAD'),
  (298, '\mantiguedad\M', 'antigüedad'),
  (299, '\mAntiguedad\M', 'Antigüedad'),
  (300, '\mAplicacion\M', 'Aplicación'),
  (301, '\maplicacion\M', 'aplicación'),
  (302, '\mAPLICACION\M', 'APLICACIÓN'),
  (303, '\mAPROBACION\M', 'APROBACIÓN'),
  (304, '\mAprobacion\M', 'Aprobación'),
  (305, '\maprobacion\M', 'aprobación'),
  (306, '\mAsignacion\M', 'Asignación'),
  (307, '\masignacion\M', 'asignación'),
  (308, '\mASIGNACION\M', 'ASIGNACIÓN'),
  (309, '\mAtribucion\M', 'Atribución'),
  (310, '\mATRIBUCION\M', 'ATRIBUCIÓN'),
  (311, '\matribucion\M', 'atribución'),
  (312, '\mAUTOMATICA\M', 'AUTOMÁTICA'),
  (313, '\mautomatica\M', 'automática'),
  (314, '\mAutomatica\M', 'Automática'),
  (315, '\mAutomatico\M', 'Automático'),
  (316, '\mAUTOMATICO\M', 'AUTOMÁTICO'),
  (317, '\mautomatico\M', 'automático'),
  (318, '\mBiometrico\M', 'Biométrico'),
  (319, '\mBIOMETRICO\M', 'BIOMÉTRICO'),
  (320, '\mbiometrico\M', 'biométrico'),
  (321, '\mContrasena\M', 'Contraseña'),
  (322, '\mCONTRASENA\M', 'CONTRASEÑA'),
  (323, '\mcontrasena\M', 'contraseña'),
  (324, '\mconversion\M', 'conversión'),
  (325, '\mConversion\M', 'Conversión'),
  (326, '\mCONVERSION\M', 'CONVERSIÓN'),
  (327, '\mCorreccion\M', 'Corrección'),
  (328, '\mcorreccion\M', 'corrección'),
  (329, '\mCORRECCION\M', 'CORRECCIÓN'),
  (330, '\mCotizacion\M', 'Cotización'),
  (331, '\mcotizacion\M', 'cotización'),
  (332, '\mCOTIZACION\M', 'COTIZACIÓN'),
  (333, '\mDEVOLUCION\M', 'DEVOLUCIÓN'),
  (334, '\mdevolucion\M', 'devolución'),
  (335, '\mDevolucion\M', 'Devolución'),
  (336, '\meditandolo\M', 'editándolo'),
  (337, '\mEditandolo\M', 'Editándolo'),
  (338, '\mEDITANDOLO\M', 'EDITÁNDOLO'),
  (339, '\mescalacion\M', 'escalación'),
  (340, '\mEscalacion\M', 'Escalación'),
  (341, '\mESCALACION\M', 'ESCALACIÓN'),
  (342, '\mEspecifico\M', 'Específico'),
  (343, '\mespecifico\M', 'específico'),
  (344, '\mESPECIFICO\M', 'ESPECÍFICO'),
  (345, '\mEstimacion\M', 'Estimación'),
  (346, '\mestimacion\M', 'estimación'),
  (347, '\mESTIMACION\M', 'ESTIMACIÓN'),
  (348, '\mEVALUACION\M', 'EVALUACIÓN'),
  (349, '\mEvaluacion\M', 'Evaluación'),
  (350, '\mevaluacion\M', 'evaluación'),
  (351, '\mexplicitos\M', 'explícitos'),
  (352, '\mEXPLICITOS\M', 'EXPLÍCITOS'),
  (353, '\mExplicitos\M', 'Explícitos'),
  (354, '\mferreteria\M', 'ferretería'),
  (355, '\mFerreteria\M', 'Ferretería'),
  (356, '\mFERRETERIA\M', 'FERRETERÍA'),
  (357, '\mfotografia\M', 'fotografía'),
  (358, '\mFotografia\M', 'Fotografía'),
  (359, '\mFOTOGRAFIA\M', 'FOTOGRAFÍA'),
  (360, '\mgeneracion\M', 'generación'),
  (361, '\mGENERACION\M', 'GENERACIÓN'),
  (362, '\mGeneracion\M', 'Generación'),
  (363, '\mINSPECCION\M', 'INSPECCIÓN'),
  (364, '\mInspeccion\M', 'Inspección'),
  (365, '\minspeccion\M', 'inspección'),
  (366, '\mINVITACION\M', 'INVITACIÓN'),
  (367, '\mInvitacion\M', 'Invitación'),
  (368, '\minvitacion\M', 'invitación'),
  (369, '\mjerarquico\M', 'jerárquico'),
  (370, '\mJerarquico\M', 'Jerárquico'),
  (371, '\mJERARQUICO\M', 'JERÁRQUICO'),
  (372, '\mlavanderia\M', 'lavandería'),
  (373, '\mLavanderia\M', 'Lavandería'),
  (374, '\mLAVANDERIA\M', 'LAVANDERÍA'),
  (375, '\mMembresias\M', 'Membresías'),
  (376, '\mmembresias\M', 'membresías'),
  (377, '\mMEMBRESIAS\M', 'MEMBRESÍAS'),
  (378, '\mobligacion\M', 'obligación'),
  (379, '\mObligacion\M', 'Obligación'),
  (380, '\mOBLIGACION\M', 'OBLIGACIÓN'),
  (381, '\mProduccion\M', 'Producción'),
  (382, '\mproduccion\M', 'producción'),
  (383, '\mPRODUCCION\M', 'PRODUCCIÓN'),
  (384, '\mpronostico\M', 'pronóstico'),
  (385, '\mPRONOSTICO\M', 'PRONÓSTICO'),
  (386, '\mPronostico\M', 'Pronóstico'),
  (387, '\mpublicaria\M', 'publicaría'),
  (388, '\mPublicaria\M', 'Publicaría'),
  (389, '\mPUBLICARIA\M', 'PUBLICARÍA'),
  (390, '\mPUNTUACION\M', 'PUNTUACIÓN'),
  (391, '\mpuntuacion\M', 'puntuación'),
  (392, '\mPuntuacion\M', 'Puntuación'),
  (393, '\mrenovacion\M', 'renovación'),
  (394, '\mRENOVACION\M', 'RENOVACIÓN'),
  (395, '\mRenovacion\M', 'Renovación'),
  (396, '\mRESOLUCION\M', 'RESOLUCIÓN'),
  (397, '\mresolucion\M', 'resolución'),
  (398, '\mResolucion\M', 'Resolución'),
  (399, '\mvalidacion\M', 'validación'),
  (400, '\mValidacion\M', 'Validación'),
  (401, '\mVALIDACION\M', 'VALIDACIÓN'),
  (402, '\mauditoria\M', 'auditoría'),
  (403, '\mAuditoria\M', 'Auditoría'),
  (404, '\mAUDITORIA\M', 'AUDITORÍA'),
  (405, '\mautografa\M', 'autógrafa'),
  (406, '\mAUTOGRAFA\M', 'AUTÓGRAFA'),
  (407, '\mAutografa\M', 'Autógrafa'),
  (408, '\mCatalogos\M', 'Catálogos'),
  (409, '\mcatalogos\M', 'catálogos'),
  (410, '\mCATALOGOS\M', 'CATÁLOGOS'),
  (411, '\mcondicion\M', 'condición'),
  (412, '\mCondicion\M', 'Condición'),
  (413, '\mCONDICION\M', 'CONDICIÓN'),
  (414, '\mDESEMPENO\M', 'DESEMPEÑO'),
  (415, '\mdesempeno\M', 'desempeño'),
  (416, '\mDesempeno\M', 'Desempeño'),
  (417, '\mDireccion\M', 'Dirección'),
  (418, '\mdireccion\M', 'dirección'),
  (419, '\mDIRECCION\M', 'DIRECCIÓN'),
  (420, '\meducacion\M', 'educación'),
  (421, '\mEducacion\M', 'Educación'),
  (422, '\mEDUCACION\M', 'EDUCACIÓN'),
  (423, '\mEJECUCION\M', 'EJECUCIÓN'),
  (424, '\mejecucion\M', 'ejecución'),
  (425, '\mEjecucion\M', 'Ejecución'),
  (426, '\mexcepcion\M', 'excepción'),
  (427, '\mExcepcion\M', 'Excepción'),
  (428, '\mEXCEPCION\M', 'EXCEPCIÓN'),
  (429, '\mExplicita\M', 'Explícita'),
  (430, '\mEXPLICITA\M', 'EXPLÍCITA'),
  (431, '\mexplicita\M', 'explícita'),
  (432, '\mExplicito\M', 'Explícito'),
  (433, '\mexplicito\M', 'explícito'),
  (434, '\mEXPLICITO\M', 'EXPLÍCITO'),
  (435, '\mExplosion\M', 'Explosión'),
  (436, '\mexplosion\M', 'explosión'),
  (437, '\mEXPLOSION\M', 'EXPLOSIÓN'),
  (438, '\mGARANTIAS\M', 'GARANTÍAS'),
  (439, '\mGarantias\M', 'Garantías'),
  (440, '\mgarantias\M', 'garantías'),
  (441, '\mHistorica\M', 'Histórica'),
  (442, '\mhistorica\M', 'histórica'),
  (443, '\mHISTORICA\M', 'HISTÓRICA'),
  (444, '\mHISTORICO\M', 'HISTÓRICO'),
  (445, '\mHistorico\M', 'Histórico'),
  (446, '\mhistorico\M', 'histórico'),
  (447, '\mHOTELERIA\M', 'HOTELERÍA'),
  (448, '\mHoteleria\M', 'Hotelería'),
  (449, '\mhoteleria\M', 'hotelería'),
  (450, '\mINFLACION\M', 'INFLACIÓN'),
  (451, '\mInflacion\M', 'Inflación'),
  (452, '\minflacion\M', 'inflación'),
  (453, '\minscribio\M', 'inscribió'),
  (454, '\mINSCRIBIO\M', 'INSCRIBIÓ'),
  (455, '\mInscribio\M', 'Inscribió'),
  (456, '\mJERARQUIA\M', 'JERARQUÍA'),
  (457, '\mJerarquia\M', 'Jerarquía'),
  (458, '\mjerarquia\M', 'jerarquía'),
  (459, '\mLOGISTICA\M', 'LOGÍSTICA'),
  (460, '\mLogistica\M', 'Logística'),
  (461, '\mlogistica\M', 'logística'),
  (462, '\mMATRICULA\M', 'MATRÍCULA'),
  (463, '\mMatricula\M', 'Matrícula'),
  (464, '\mmatricula\M', 'matrícula'),
  (465, '\mMERCANCIA\M', 'MERCANCÍA'),
  (466, '\mMercancia\M', 'Mercancía'),
  (467, '\mmercancia\M', 'mercancía'),
  (468, '\mpoliticas\M', 'políticas'),
  (469, '\mPoliticas\M', 'Políticas'),
  (470, '\mPOLITICAS\M', 'POLÍTICAS'),
  (471, '\mprestamos\M', 'préstamos'),
  (472, '\mPrestamos\M', 'Préstamos'),
  (473, '\mPRESTAMOS\M', 'PRÉSTAMOS'),
  (474, '\mPROMOCION\M', 'PROMOCIÓN'),
  (475, '\mpromocion\M', 'promoción'),
  (476, '\mPromocion\M', 'Promoción'),
  (477, '\mProposito\M', 'Propósito'),
  (478, '\mproposito\M', 'propósito'),
  (479, '\mPROPOSITO\M', 'PROPÓSITO'),
  (480, '\mRecepcion\M', 'Recepción'),
  (481, '\mrecepcion\M', 'recepción'),
  (482, '\mRECEPCION\M', 'RECEPCIÓN'),
  (483, '\mResumenes\M', 'Resúmenes'),
  (484, '\mresumenes\M', 'resúmenes'),
  (485, '\mRESUMENES\M', 'RESÚMENES'),
  (486, '\mretencion\M', 'retención'),
  (487, '\mRETENCION\M', 'RETENCIÓN'),
  (488, '\mRetencion\M', 'Retención'),
  (489, '\mRevisalas\M', 'Revísalas'),
  (490, '\mrevisalas\M', 'revísalas'),
  (491, '\mREVISALAS\M', 'REVÍSALAS'),
  (492, '\mSUPERAVIT\M', 'SUPERÁVIT'),
  (493, '\mSuperavit\M', 'Superávit'),
  (494, '\msuperavit\M', 'superávit'),
  (495, '\mtesoreria\M', 'tesorería'),
  (496, '\mTESORERIA\M', 'TESORERÍA'),
  (497, '\mTesoreria\M', 'Tesorería'),
  (498, '\mVehiculos\M', 'Vehículos'),
  (499, '\mvehiculos\M', 'vehículos'),
  (500, '\mVEHICULOS\M', 'VEHÍCULOS'),
  (501, '\mbitacora\M', 'bitácora'),
  (502, '\mBITACORA\M', 'BITÁCORA'),
  (503, '\mBitacora\M', 'Bitácora'),
  (504, '\mBUSQUEDA\M', 'BÚSQUEDA'),
  (505, '\mbusqueda\M', 'búsqueda'),
  (506, '\mBusqueda\M', 'Búsqueda'),
  (507, '\mCampanas\M', 'Campañas'),
  (508, '\mcampanas\M', 'campañas'),
  (509, '\mCAMPANAS\M', 'CAMPAÑAS'),
  (510, '\mCATALOGO\M', 'CATÁLOGO'),
  (511, '\mcatalogo\M', 'catálogo'),
  (512, '\mCatalogo\M', 'Catálogo'),
  (513, '\mCESANTIA\M', 'CESANTÍA'),
  (514, '\mcesantia\M', 'cesantía'),
  (515, '\mCesantia\M', 'Cesantía'),
  (516, '\mciclicos\M', 'cíclicos'),
  (517, '\mCICLICOS\M', 'CÍCLICOS'),
  (518, '\mCiclicos\M', 'Cíclicos'),
  (519, '\mcomision\M', 'comisión'),
  (520, '\mComision\M', 'Comisión'),
  (521, '\mCOMISION\M', 'COMISIÓN'),
  (522, '\mCompania\M', 'Compañía'),
  (523, '\mcompania\M', 'compañía'),
  (524, '\mCOMPANIA\M', 'COMPAÑÍA'),
  (525, '\mconexion\M', 'conexión'),
  (526, '\mConexion\M', 'Conexión'),
  (527, '\mCONEXION\M', 'CONEXIÓN'),
  (528, '\mCorrigio\M', 'Corrigió'),
  (529, '\mcorrigio\M', 'corrigió'),
  (530, '\mCORRIGIO\M', 'CORRIGIÓ'),
  (531, '\mDEBERIAN\M', 'DEBERÍAN'),
  (532, '\mDeberian\M', 'Deberían'),
  (533, '\mdeberian\M', 'deberían'),
  (534, '\mdecision\M', 'decisión'),
  (535, '\mDecision\M', 'Decisión'),
  (536, '\mDECISION\M', 'DECISIÓN'),
  (537, '\mdeposito\M', 'depósito'),
  (538, '\mDEPOSITO\M', 'DEPÓSITO'),
  (539, '\mDeposito\M', 'Depósito'),
  (540, '\mdevolvio\M', 'devolvió'),
  (541, '\mDEVOLVIO\M', 'DEVOLVIÓ'),
  (542, '\mDevolvio\M', 'Devolvió'),
  (543, '\mDisenado\M', 'Diseñado'),
  (544, '\mdisenado\M', 'diseñado'),
  (545, '\mDISENADO\M', 'DISEÑADO'),
  (546, '\mESCRIBIO\M', 'ESCRIBIÓ'),
  (547, '\mEscribio\M', 'Escribió'),
  (548, '\mescribio\M', 'escribió'),
  (549, '\metiqueto\M', 'etiquetó'),
  (550, '\mETIQUETO\M', 'ETIQUETÓ'),
  (551, '\mEtiqueto\M', 'Etiquetó'),
  (552, '\mEXISTIAN\M', 'EXISTÍAN'),
  (553, '\mexistian\M', 'existían'),
  (554, '\mExistian\M', 'Existían'),
  (555, '\mEXTRAIDO\M', 'EXTRAÍDO'),
  (556, '\mextraido\M', 'extraído'),
  (557, '\mExtraido\M', 'Extraído'),
  (558, '\mFUNCIONO\M', 'FUNCIONÓ'),
  (559, '\mfunciono\M', 'funcionó'),
  (560, '\mFunciono\M', 'Funcionó'),
  (561, '\mGarantia\M', 'Garantía'),
  (562, '\mGARANTIA\M', 'GARANTÍA'),
  (563, '\mgarantia\M', 'garantía'),
  (564, '\mgenerica\M', 'genérica'),
  (565, '\mGENERICA\M', 'GENÉRICA'),
  (566, '\mGenerica\M', 'Genérica'),
  (567, '\mGENERICO\M', 'GENÉRICO'),
  (568, '\mgenerico\M', 'genérico'),
  (569, '\mGenerico\M', 'Genérico'),
  (570, '\mIdentico\M', 'Idéntico'),
  (571, '\mIDENTICO\M', 'IDÉNTICO'),
  (572, '\midentico\M', 'idéntico'),
  (573, '\mIMAGENES\M', 'IMÁGENES'),
  (574, '\mimagenes\M', 'imágenes'),
  (575, '\mImagenes\M', 'Imágenes'),
  (576, '\mposicion\M', 'posición'),
  (577, '\mPOSICION\M', 'POSICIÓN'),
  (578, '\mPosicion\M', 'Posición'),
  (579, '\mPRESTAMO\M', 'PRÉSTAMO'),
  (580, '\mPrestamo\M', 'Préstamo'),
  (581, '\mprestamo\M', 'préstamo'),
  (582, '\mQuimicos\M', 'Químicos'),
  (583, '\mquimicos\M', 'químicos'),
  (584, '\mQUIMICOS\M', 'QUÍMICOS'),
  (585, '\mREVISION\M', 'REVISIÓN'),
  (586, '\mRevision\M', 'Revisión'),
  (587, '\mrevision\M', 'revisión'),
  (588, '\mtecnicos\M', 'técnicos'),
  (589, '\mTECNICOS\M', 'TÉCNICOS'),
  (590, '\mTecnicos\M', 'Técnicos'),
  (591, '\mtelefono\M', 'teléfono'),
  (592, '\mTELEFONO\M', 'TELÉFONO'),
  (593, '\mTelefono\M', 'Teléfono'),
  (594, '\mterminos\M', 'términos'),
  (595, '\mTerminos\M', 'Términos'),
  (596, '\mTERMINOS\M', 'TÉRMINOS'),
  (597, '\mTRANSITO\M', 'TRÁNSITO'),
  (598, '\mtransito\M', 'tránsito'),
  (599, '\mTransito\M', 'Tránsito'),
  (600, '\mVEHICULO\M', 'VEHÍCULO'),
  (601, '\mvehiculo\M', 'vehículo'),
  (602, '\mVehiculo\M', 'Vehículo'),
  (603, '\malmacen\M', 'almacén'),
  (604, '\mAlmacen\M', 'Almacén'),
  (605, '\mALMACEN\M', 'ALMACÉN'),
  (606, '\matendio\M', 'atendió'),
  (607, '\mATENDIO\M', 'ATENDIÓ'),
  (608, '\mAtendio\M', 'Atendió'),
  (609, '\mCalculo\M', 'Cálculo'),
  (610, '\mCALCULO\M', 'CÁLCULO'),
  (611, '\mcalculo\M', 'cálculo'),
  (612, '\mCAMPANA\M', 'CAMPAÑA'),
  (613, '\mcampana\M', 'campaña'),
  (614, '\mCampana\M', 'Campaña'),
  (615, '\mClasica\M', 'Clásica'),
  (616, '\mclasica\M', 'clásica'),
  (617, '\mCLASICA\M', 'CLÁSICA'),
  (618, '\mCLINICA\M', 'CLÍNICA'),
  (619, '\mClinica\M', 'Clínica'),
  (620, '\mclinica\M', 'clínica'),
  (621, '\mCODIGOS\M', 'CÓDIGOS'),
  (622, '\mcodigos\M', 'códigos'),
  (623, '\mCodigos\M', 'Códigos'),
  (624, '\mCredito\M', 'Crédito'),
  (625, '\mcredito\M', 'crédito'),
  (626, '\mCREDITO\M', 'CRÉDITO'),
  (627, '\mCRITICO\M', 'CRÍTICO'),
  (628, '\mCritico\M', 'Crítico'),
  (629, '\mcritico\M', 'crítico'),
  (630, '\mCumplio\M', 'Cumplió'),
  (631, '\mcumplio\M', 'cumplió'),
  (632, '\mCUMPLIO\M', 'CUMPLIÓ'),
  (633, '\mdanados\M', 'dañados'),
  (634, '\mDANADOS\M', 'DAÑADOS'),
  (635, '\mDanados\M', 'Dañados'),
  (636, '\mdeberia\M', 'debería'),
  (637, '\mDEBERIA\M', 'DEBERÍA'),
  (638, '\mDeberia\M', 'Debería'),
  (639, '\mDeficit\M', 'Déficit'),
  (640, '\mdeficit\M', 'déficit'),
  (641, '\mDEFICIT\M', 'DÉFICIT'),
  (642, '\mdespues\M', 'después'),
  (643, '\mDESPUES\M', 'DESPUÉS'),
  (644, '\mDespues\M', 'Después'),
  (645, '\mDialogo\M', 'Diálogo'),
  (646, '\mDIALOGO\M', 'DIÁLOGO'),
  (647, '\mdialogo\M', 'diálogo'),
  (648, '\mDificil\M', 'Difícil'),
  (649, '\mdificil\M', 'difícil'),
  (650, '\mDIFICIL\M', 'DIFÍCIL'),
  (651, '\mDolares\M', 'Dólares'),
  (652, '\mDOLARES\M', 'DÓLARES'),
  (653, '\mdolares\M', 'dólares'),
  (654, '\memision\M', 'emisión'),
  (655, '\mEMISION\M', 'EMISIÓN'),
  (656, '\mEmision\M', 'Emisión'),
  (657, '\mescaner\M', 'escáner'),
  (658, '\mEscaner\M', 'Escáner'),
  (659, '\mESCANER\M', 'ESCÁNER'),
  (660, '\mespanol\M', 'español'),
  (661, '\mEspanol\M', 'Español'),
  (662, '\mESPANOL\M', 'ESPAÑOL'),
  (663, '\mFISICAS\M', 'FÍSICAS'),
  (664, '\mfisicas\M', 'físicas'),
  (665, '\mFisicas\M', 'Físicas'),
  (666, '\mFISICOS\M', 'FÍSICOS'),
  (667, '\mfisicos\M', 'físicos'),
  (668, '\mFisicos\M', 'Físicos'),
  (669, '\mFormula\M', 'Fórmula'),
  (670, '\mformula\M', 'fórmula'),
  (671, '\mFORMULA\M', 'FÓRMULA'),
  (672, '\mFRANCES\M', 'FRANCÉS'),
  (673, '\mFrances\M', 'Francés'),
  (674, '\mfrances\M', 'francés'),
  (675, '\mFuncion\M', 'Función'),
  (676, '\mfuncion\M', 'función'),
  (677, '\mFUNCION\M', 'FUNCIÓN'),
  (678, '\mInteres\M', 'Interés'),
  (679, '\mINTERES\M', 'INTERÉS'),
  (680, '\minteres\M', 'interés'),
  (681, '\mLLEVATE\M', 'LLÉVATE'),
  (682, '\mllevate\M', 'llévate'),
  (683, '\mLlevate\M', 'Llévate'),
  (684, '\mmaquina\M', 'máquina'),
  (685, '\mMAQUINA\M', 'MÁQUINA'),
  (686, '\mMaquina\M', 'Máquina'),
  (687, '\mMayoria\M', 'Mayoría'),
  (688, '\mMAYORIA\M', 'MAYORÍA'),
  (689, '\mmayoria\M', 'mayoría'),
  (690, '\mmedicos\M', 'médicos'),
  (691, '\mMEDICOS\M', 'MÉDICOS'),
  (692, '\mMedicos\M', 'Médicos'),
  (693, '\mMetodos\M', 'Métodos'),
  (694, '\mmetodos\M', 'métodos'),
  (695, '\mMETODOS\M', 'MÉTODOS'),
  (696, '\mMinimos\M', 'Mínimos'),
  (697, '\mminimos\M', 'mínimos'),
  (698, '\mMINIMOS\M', 'MÍNIMOS'),
  (699, '\mModulos\M', 'Módulos'),
  (700, '\mMODULOS\M', 'MÓDULOS'),
  (701, '\mmodulos\M', 'módulos'),
  (702, '\mnominas\M', 'nóminas'),
  (703, '\mNOMINAS\M', 'NÓMINAS'),
  (704, '\mNominas\M', 'Nóminas'),
  (705, '\mNUMEROS\M', 'NÚMEROS'),
  (706, '\mNumeros\M', 'Números'),
  (707, '\mnumeros\M', 'números'),
  (708, '\mOcurrio\M', 'Ocurrió'),
  (709, '\mOCURRIO\M', 'OCURRIÓ'),
  (710, '\mocurrio\M', 'ocurrió'),
  (711, '\mofrecio\M', 'ofreció'),
  (712, '\mOfrecio\M', 'Ofreció'),
  (713, '\mOFRECIO\M', 'OFRECIÓ'),
  (714, '\mOrdenes\M', 'Órdenes'),
  (715, '\mORDENES\M', 'ÓRDENES'),
  (716, '\mordenes\M', 'órdenes'),
  (717, '\mPediria\M', 'Pediría'),
  (718, '\mPEDIRIA\M', 'PEDIRÍA'),
  (719, '\mpediria\M', 'pediría'),
  (720, '\mPODRIAN\M', 'PODRÍAN'),
  (721, '\mPodrian\M', 'Podrían'),
  (722, '\mpodrian\M', 'podrían'),
  (723, '\mProximo\M', 'Próximo'),
  (724, '\mPROXIMO\M', 'PRÓXIMO'),
  (725, '\mproximo\M', 'próximo'),
  (726, '\mPUBLICO\M', 'PÚBLICO'),
  (727, '\mPublico\M', 'Público'),
  (728, '\mpublico\M', 'público'),
  (729, '\mRecibio\M', 'Recibió'),
  (730, '\mRECIBIO\M', 'RECIBIÓ'),
  (731, '\mrecibio\M', 'recibió'),
  (732, '\mREENVIA\M', 'REENVÍA'),
  (733, '\mReenvia\M', 'Reenvía'),
  (734, '\mreenvia\M', 'reenvía'),
  (735, '\mREGALIA\M', 'REGALÍA'),
  (736, '\mregalia\M', 'regalía'),
  (737, '\mRegalia\M', 'Regalía'),
  (738, '\mReunion\M', 'Reunión'),
  (739, '\mREUNION\M', 'REUNIÓN'),
  (740, '\mreunion\M', 'reunión'),
  (741, '\mrevaluo\M', 'revalúo'),
  (742, '\mREVALUO\M', 'REVALÚO'),
  (743, '\mRevaluo\M', 'Revalúo'),
  (744, '\mTAMBIEN\M', 'TAMBIÉN'),
  (745, '\mtambien\M', 'también'),
  (746, '\mTambien\M', 'También'),
  (747, '\mTecnico\M', 'Técnico'),
  (748, '\mtecnico\M', 'técnico'),
  (749, '\mTECNICO\M', 'TÉCNICO'),
  (750, '\mtermica\M', 'térmica'),
  (751, '\mTermica\M', 'Térmica'),
  (752, '\mTERMICA\M', 'TÉRMICA'),
  (753, '\mTodavia\M', 'Todavía'),
  (754, '\mTODAVIA\M', 'TODAVÍA'),
  (755, '\mtodavia\M', 'todavía'),
  (756, '\mTRAMITE\M', 'TRÁMITE'),
  (757, '\mtramite\M', 'trámite'),
  (758, '\mTramite\M', 'Trámite'),
  (759, '\mValdria\M', 'Valdría'),
  (760, '\mVALDRIA\M', 'VALDRÍA'),
  (761, '\mvaldria\M', 'valdría'),
  (762, '\mVERSION\M', 'VERSIÓN'),
  (763, '\mVersion\M', 'Versión'),
  (764, '\mversion\M', 'versión'),
  (765, '\mVinculo\M', 'Vínculo'),
  (766, '\mvinculo\M', 'vínculo'),
  (767, '\mVINCULO\M', 'VÍNCULO'),
  (768, '\mAccion\M', 'Acción'),
  (769, '\maccion\M', 'acción'),
  (770, '\mACCION\M', 'ACCIÓN'),
  (771, '\mADEMAS\M', 'ADEMÁS'),
  (772, '\mAdemas\M', 'Además'),
  (773, '\mademas\M', 'además'),
  (774, '\mAMBITO\M', 'ÁMBITO'),
  (775, '\mAmbito\M', 'Ámbito'),
  (776, '\mambito\M', 'ámbito'),
  (777, '\mAprobo\M', 'Aprobó'),
  (778, '\mAPROBO\M', 'APROBÓ'),
  (779, '\maprobo\M', 'aprobó'),
  (780, '\mAVALUO\M', 'AVALÚO'),
  (781, '\mAvaluo\M', 'Avalúo'),
  (782, '\mavaluo\M', 'avalúo'),
  (783, '\mBASICA\M', 'BÁSICA'),
  (784, '\mBasica\M', 'Básica'),
  (785, '\mbasica\M', 'básica'),
  (786, '\mCamara\M', 'Cámara'),
  (787, '\mcamara\M', 'cámara'),
  (788, '\mCAMARA\M', 'CÁMARA'),
  (789, '\mCAMION\M', 'CAMIÓN'),
  (790, '\mcamion\M', 'camión'),
  (791, '\mCamion\M', 'Camión'),
  (792, '\mcedula\M', 'cédula'),
  (793, '\mCEDULA\M', 'CÉDULA'),
  (794, '\mCedula\M', 'Cédula'),
  (795, '\mCodigo\M', 'Código'),
  (796, '\mcodigo\M', 'código'),
  (797, '\mCODIGO\M', 'CÓDIGO'),
  (798, '\mConfia\M', 'Confía'),
  (799, '\mconfia\M', 'confía'),
  (800, '\mCONFIA\M', 'CONFÍA'),
  (801, '\mDEBITO\M', 'DÉBITO'),
  (802, '\mdebito\M', 'débito'),
  (803, '\mDebito\M', 'Débito'),
  (804, '\mdigito\M', 'dígito'),
  (805, '\mDigito\M', 'Dígito'),
  (806, '\mDIGITO\M', 'DÍGITO'),
  (807, '\mdiseno\M', 'diseño'),
  (808, '\mDISENO\M', 'DISEÑO'),
  (809, '\mDiseno\M', 'Diseño'),
  (810, '\mEligio\M', 'Eligió'),
  (811, '\meligio\M', 'eligió'),
  (812, '\mELIGIO\M', 'ELIGIÓ'),
  (813, '\memitio\M', 'emitió'),
  (814, '\mEMITIO\M', 'EMITIÓ'),
  (815, '\mEmitio\M', 'Emitió'),
  (816, '\mfisica\M', 'física'),
  (817, '\mFisica\M', 'Física'),
  (818, '\mFISICA\M', 'FÍSICA'),
  (819, '\mFISICO\M', 'FÍSICO'),
  (820, '\mFisico\M', 'Físico'),
  (821, '\mfisico\M', 'físico'),
  (822, '\mHabias\M', 'Habías'),
  (823, '\mHABIAS\M', 'HABÍAS'),
  (824, '\mhabias\M', 'habías'),
  (825, '\mHABRIA\M', 'HABRÍA'),
  (826, '\mhabria\M', 'habría'),
  (827, '\mHabria\M', 'Habría'),
  (828, '\mHarias\M', 'Harías'),
  (829, '\mHARIAS\M', 'HARÍAS'),
  (830, '\mharias\M', 'harías'),
  (831, '\mINUTIL\M', 'INÚTIL'),
  (832, '\minutil\M', 'inútil'),
  (833, '\mInutil\M', 'Inútil'),
  (834, '\mlimite\M', 'límite'),
  (835, '\mLimite\M', 'Límite'),
  (836, '\mLIMITE\M', 'LÍMITE'),
  (837, '\mLINEAS\M', 'LÍNEAS'),
  (838, '\mlineas\M', 'líneas'),
  (839, '\mLineas\M', 'Líneas'),
  (840, '\mlogica\M', 'lógica'),
  (841, '\mLOGICA\M', 'LÓGICA'),
  (842, '\mLogica\M', 'Lógica'),
  (843, '\mMAGICO\M', 'MÁGICO'),
  (844, '\mMagico\M', 'Mágico'),
  (845, '\mmagico\M', 'mágico'),
  (846, '\mMANANA\M', 'MAÑANA'),
  (847, '\mManana\M', 'Mañana'),
  (848, '\mmanana\M', 'mañana'),
  (849, '\mMedica\M', 'Médica'),
  (850, '\mMEDICA\M', 'MÉDICA'),
  (851, '\mmedica\M', 'médica'),
  (852, '\mMETODO\M', 'MÉTODO'),
  (853, '\mMetodo\M', 'Método'),
  (854, '\mmetodo\M', 'método'),
  (855, '\mMINIMO\M', 'MÍNIMO'),
  (856, '\mminimo\M', 'mínimo'),
  (857, '\mMinimo\M', 'Mínimo'),
  (858, '\mMODULO\M', 'MÓDULO'),
  (859, '\mmodulo\M', 'módulo'),
  (860, '\mModulo\M', 'Módulo'),
  (861, '\mningun\M', 'ningún'),
  (862, '\mNingun\M', 'Ningún'),
  (863, '\mNINGUN\M', 'NINGÚN'),
  (864, '\mnomina\M', 'nómina'),
  (865, '\mNOMINA\M', 'NÓMINA'),
  (866, '\mNomina\M', 'Nómina'),
  (867, '\mNUMERO\M', 'NÚMERO'),
  (868, '\mNumero\M', 'Número'),
  (869, '\mnumero\M', 'número'),
  (870, '\mOpcion\M', 'Opción'),
  (871, '\mopcion\M', 'opción'),
  (872, '\mOPCION\M', 'OPCIÓN'),
  (873, '\moptico\M', 'óptico'),
  (874, '\mOPTICO\M', 'ÓPTICO'),
  (875, '\mOptico\M', 'Óptico'),
  (876, '\mPagina\M', 'Página'),
  (877, '\mpagina\M', 'página'),
  (878, '\mPAGINA\M', 'PÁGINA'),
  (879, '\mperdio\M', 'perdió'),
  (880, '\mPerdio\M', 'Perdió'),
  (881, '\mPERDIO\M', 'PERDIÓ'),
  (882, '\mpodran\M', 'podrán'),
  (883, '\mPodran\M', 'Podrán'),
  (884, '\mPODRAN\M', 'PODRÁN'),
  (885, '\mPodria\M', 'Podría'),
  (886, '\mPODRIA\M', 'PODRÍA'),
  (887, '\mpodria\M', 'podría'),
  (888, '\mRAPIDA\M', 'RÁPIDA'),
  (889, '\mrapida\M', 'rápida'),
  (890, '\mRapida\M', 'Rápida'),
  (891, '\mRAPIDO\M', 'RÁPIDO'),
  (892, '\mRapido\M', 'Rápido'),
  (893, '\mrapido\M', 'rápido'),
  (894, '\mRecien\M', 'Recién'),
  (895, '\mrecien\M', 'recién'),
  (896, '\mRECIEN\M', 'RECIÉN'),
  (897, '\msabado\M', 'sábado'),
  (898, '\mSABADO\M', 'SÁBADO'),
  (899, '\mSabado\M', 'Sábado'),
  (900, '\msesion\M', 'sesión'),
  (901, '\mSesion\M', 'Sesión'),
  (902, '\mSESION\M', 'SESIÓN'),
  (903, '\mtactil\M', 'táctil'),
  (904, '\mTactil\M', 'Táctil'),
  (905, '\mTACTIL\M', 'TÁCTIL'),
  (906, '\mTenian\M', 'Tenían'),
  (907, '\mtenian\M', 'tenían'),
  (908, '\mTENIAN\M', 'TENÍAN'),
  (909, '\mTENIAS\M', 'TENÍAS'),
  (910, '\mTenias\M', 'Tenías'),
  (911, '\mtenias\M', 'tenías'),
  (912, '\mTipico\M', 'Típico'),
  (913, '\mtipico\M', 'típico'),
  (914, '\mTIPICO\M', 'TÍPICO'),
  (915, '\mUltima\M', 'Última'),
  (916, '\multima\M', 'última'),
  (917, '\mULTIMA\M', 'ÚLTIMA'),
  (918, '\mULTIMO\M', 'ÚLTIMO'),
  (919, '\multimo\M', 'último'),
  (920, '\mUltimo\M', 'Último'),
  (921, '\mVENCIO\M', 'VENCIÓ'),
  (922, '\mVencio\M', 'Venció'),
  (923, '\mvencio\M', 'venció'),
  (924, '\mvendio\M', 'vendió'),
  (925, '\mVENDIO\M', 'VENDIÓ'),
  (926, '\mVendio\M', 'Vendió'),
  (927, '\mVision\M', 'Visión'),
  (928, '\mvision\M', 'visión'),
  (929, '\mVISION\M', 'VISIÓN'),
  (930, '\mAMBAR\M', 'ÁMBAR'),
  (931, '\mAmbar\M', 'Ámbar'),
  (932, '\mambar\M', 'ámbar'),
  (933, '\mARBOL\M', 'ÁRBOL'),
  (934, '\marbol\M', 'árbol'),
  (935, '\mArbol\M', 'Árbol'),
  (936, '\mAtras\M', 'Atrás'),
  (937, '\mATRAS\M', 'ATRÁS'),
  (938, '\matras\M', 'atrás'),
  (939, '\mBoton\M', 'Botón'),
  (940, '\mBOTON\M', 'BOTÓN'),
  (941, '\mboton\M', 'botón'),
  (942, '\mBUZON\M', 'BUZÓN'),
  (943, '\mbuzon\M', 'buzón'),
  (944, '\mBuzon\M', 'Buzón'),
  (945, '\mCaida\M', 'Caída'),
  (946, '\mcaida\M', 'caída'),
  (947, '\mCAIDA\M', 'CAÍDA'),
  (948, '\mcomun\M', 'común'),
  (949, '\mCOMUN\M', 'COMÚN'),
  (950, '\mComun\M', 'Común'),
  (951, '\mCupon\M', 'Cupón'),
  (952, '\mCUPON\M', 'CUPÓN'),
  (953, '\mcupon\M', 'cupón'),
  (954, '\mDEBIO\M', 'DEBIÓ'),
  (955, '\mDebio\M', 'Debió'),
  (956, '\mdebio\M', 'debió'),
  (957, '\mdueno\M', 'dueño'),
  (958, '\mDueno\M', 'Dueño'),
  (959, '\mDUENO\M', 'DUEÑO'),
  (960, '\menvia\M', 'envía'),
  (961, '\mEnvia\M', 'Envía'),
  (962, '\mENVIA\M', 'ENVÍA'),
  (963, '\mENVIO\M', 'ENVÍO'),
  (964, '\menvio\M', 'envío'),
  (965, '\mEnvio\M', 'Envío'),
  (966, '\mestan\M', 'están'),
  (967, '\mESTAN\M', 'ESTÁN'),
  (968, '\mEstan\M', 'Están'),
  (969, '\mesten\M', 'estén'),
  (970, '\mEsten\M', 'Estén'),
  (971, '\mESTEN\M', 'ESTÉN'),
  (972, '\mFACIL\M', 'FÁCIL'),
  (973, '\mFacil\M', 'Fácil'),
  (974, '\mfacil\M', 'fácil'),
  (975, '\mFirmo\M', 'Firmó'),
  (976, '\mfirmo\M', 'firmó'),
  (977, '\mFIRMO\M', 'FIRMÓ'),
  (978, '\mfrios\M', 'fríos'),
  (979, '\mFRIOS\M', 'FRÍOS'),
  (980, '\mFrios\M', 'Fríos'),
  (981, '\mlinea\M', 'línea'),
  (982, '\mLinea\M', 'Línea'),
  (983, '\mLINEA\M', 'LÍNEA'),
  (984, '\mLLEGO\M', 'LLEGÓ'),
  (985, '\mllego\M', 'llegó'),
  (986, '\mLlego\M', 'Llegó'),
  (987, '\mmenus\M', 'menús'),
  (988, '\mMenus\M', 'Menús'),
  (989, '\mMENUS\M', 'MENÚS'),
  (990, '\mnacio\M', 'nació'),
  (991, '\mNacio\M', 'Nació'),
  (992, '\mNACIO\M', 'NACIÓ'),
  (993, '\mPidio\M', 'Pidió'),
  (994, '\mpidio\M', 'pidió'),
  (995, '\mPIDIO\M', 'PIDIÓ'),
  (996, '\mPodra\M', 'Podrá'),
  (997, '\mpodra\M', 'podrá'),
  (998, '\mPODRA\M', 'PODRÁ'),
  (999, '\mquedo\M', 'quedó'),
  (1000, '\mQUEDO\M', 'QUEDÓ'),
  (1001, '\mQuedo\M', 'Quedó'),
  (1002, '\mrazon\M', 'razón'),
  (1003, '\mRAZON\M', 'RAZÓN'),
  (1004, '\mRazon\M', 'Razón'),
  (1005, '\mReves\M', 'Revés'),
  (1006, '\mreves\M', 'revés'),
  (1007, '\mREVES\M', 'REVÉS'),
  (1008, '\mSalio\M', 'Salió'),
  (1009, '\msalio\M', 'salió'),
  (1010, '\mSALIO\M', 'SALIÓ'),
  (1011, '\mSEGUN\M', 'SEGÚN'),
  (1012, '\msegun\M', 'según'),
  (1013, '\mSegun\M', 'Según'),
  (1014, '\mSenal\M', 'Señal'),
  (1015, '\msenal\M', 'señal'),
  (1016, '\mSENAL\M', 'SEÑAL'),
  (1017, '\mTenia\M', 'Tenía'),
  (1018, '\mtenia\M', 'tenía'),
  (1019, '\mTENIA\M', 'TENÍA'),
  (1020, '\mUNICA\M', 'ÚNICA'),
  (1021, '\munica\M', 'única'),
  (1022, '\mUnica\M', 'Única'),
  (1023, '\mUNICO\M', 'ÚNICO'),
  (1024, '\mUnico\M', 'Único'),
  (1025, '\munico\M', 'único'),
  (1026, '\mveria\M', 'vería'),
  (1027, '\mVERIA\M', 'VERÍA'),
  (1028, '\mVeria\M', 'Vería'),
  (1029, '\mAlli\M', 'Allí'),
  (1030, '\mALLI\M', 'ALLÍ'),
  (1031, '\malli\M', 'allí'),
  (1032, '\mANOS\M', 'AÑOS'),
  (1033, '\mAnos\M', 'Años'),
  (1034, '\manos\M', 'años'),
  (1035, '\mAqui\M', 'Aquí'),
  (1036, '\maqui\M', 'aquí'),
  (1037, '\mAQUI\M', 'AQUÍ'),
  (1038, '\mDias\M', 'Días'),
  (1039, '\mdias\M', 'días'),
  (1040, '\mDIAS\M', 'DÍAS'),
  (1041, '\mRAIZ\M', 'RAÍZ'),
  (1042, '\mRaiz\M', 'Raíz'),
  (1043, '\mraiz\M', 'raíz'),
  (1044, '\mutil\M', 'útil'),
  (1045, '\mUTIL\M', 'ÚTIL'),
  (1046, '\mUtil\M', 'Útil'),
  (1047, '\mahi\M', 'ahí'),
  (1048, '\mAHI\M', 'AHÍ'),
  (1049, '\mAhi\M', 'Ahí'),
  (1050, '\mAno\M', 'Año'),
  (1051, '\mANO\M', 'AÑO'),
  (1052, '\mano\M', 'año'),
  (1053, '\masi\M', 'así'),
  (1054, '\mASI\M', 'ASÍ'),
  (1055, '\mAsi\M', 'Así'),
  (1056, '\mDIA\M', 'DÍA'),
  (1057, '\mdia\M', 'día'),
  (1058, '\mDia\M', 'Día'),
  (1059, '\mmas\M', 'más'),
  (1060, '\mMAS\M', 'MÁS'),
  (1061, '\mMas\M', 'Más'),
  (1062, '\mVIA\M', 'VÍA'),
  (1063, '\mVia\M', 'Vía'),
  (1064, '\mvia\M', 'vía'),
  (1065, '\mesta\M(?=( (apagado|apagada|en|disponible|impuesto|inscrito|inscrita|conectado|conectada|dicho|activa|activo|ahí|de cada|construido|construida|decidido|decidida|fallando|preparada|preparado|bien|listo|lista|declarado|declarada|permitido|homologado|fuera|certificado|cada|usando|"en)\M|[,?]))', 'está'),
  (1066, '\mcuanto\M', 'cuánto'),
  (1067, '\mCuanto\M', 'Cuánto'),
  (1068, '\mcuantos\M', 'cuántos'),
  (1069, '\mcuantas\M', 'cuántas'),
  (1070, '\men cuánto\M', 'en cuanto'),
  (1071, '\mcuánto antes\M', 'cuanto antes'),
  (1072, '\mSi(,|\.|:| -)', 'Sí\1'),
  (1073, '\msi([.:])', 'sí\1'),
  (1074, '\mentre si\M', 'entre sí');

create function pg_temp.tildes_0134(t text) returns text
language plpgsql
as $$
declare
  r record;
  s text := t;
begin
  if s is null or s = '' then
    return s;
  end if;
  for r in select patron, reemplazo from tildes_0134 order by orden loop
    s := regexp_replace(s, r.patron, r.reemplazo, 'g');
  end loop;
  return s;
end;
$$;

update regb.module_catalog mc
set
  name = pg_temp.tildes_0134(mc.name),
  description = pg_temp.tildes_0134(mc.description),
  tagline = pg_temp.tildes_0134(mc.tagline),
  problem = pg_temp.tildes_0134(mc.problem),
  audience = coalesce(
    (select array_agg(pg_temp.tildes_0134(a) order by i)
     from unnest(mc.audience) with ordinality as u(a, i)),
    mc.audience),
  -- `jsonb_strip_nulls` para no inventar claves que la ficha no tenia.
  features = coalesce(
    (select jsonb_agg(
              f || jsonb_strip_nulls(jsonb_build_object(
                     'titulo', pg_temp.tildes_0134(f->>'titulo'),
                     'detalle', pg_temp.tildes_0134(f->>'detalle')))
              order by i)
     from jsonb_array_elements(mc.features) with ordinality as e(f, i)),
    mc.features),
  faq = coalesce(
    (select jsonb_agg(
              f || jsonb_strip_nulls(jsonb_build_object(
                     'p', pg_temp.tildes_0134(f->>'p'),
                     'r', pg_temp.tildes_0134(f->>'r')))
              order by i)
     from jsonb_array_elements(mc.faq) with ordinality as e(f, i)),
    mc.faq),
  screens = coalesce(
    (select jsonb_agg(
              f || jsonb_strip_nulls(jsonb_build_object(
                     'titulo', pg_temp.tildes_0134(f->>'titulo'),
                     'descripcion', pg_temp.tildes_0134(f->>'descripcion')))
              order by i)
     from jsonb_array_elements(mc.screens) with ordinality as e(f, i)),
    mc.screens);

drop function pg_temp.tildes_0134(text);
